### ISSUE TITLE
After running the bot gives this crash

### ISSUE THREAD

**Issue by raymand211092** [simplebot-org/simplebot#136]
name = 'deltachat_ffi'
operating_system = 'unix:Ubuntu'
crate_version = '1.101.0'
explanation = '''
Panic occurred in file '/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/time/driver/entry.rs' at line 394
'''
cause = 'Timer already fired'
method = 'Panic'
backtrace = '''

   0: 0x7f2d3b5f31db - core::panicking::panic_str::h98ed104b0c03a108
                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:56
   1: 0x7f2d3b3668d6 - core::option::expect_failed::h58d487f78ae9d247
                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/option.rs:1874
   2: 0x7f2d3bedb3d3 - tokio::time::driver::entry::TimerEntry::reset::hbbcccd7f9465b576
   3: 0x7f2d3bee97a3 - <tokio::time::driver::sleep::Sleep as core::future::future::Future>::poll::h4c733a398cccea7a
   4: 0x7f2d3b4062db - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h262d9fd449c43745
   5: 0x7f2d3b822cb0 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h8e9acae4f2a0b007
   6: 0x7f2d3b8cce44 - tokio::runtime::task::raw::poll::h91b1edf4cf1ff0e4
   7: 0x7f2d3bed5c4d - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hecfd6b2c01e05a3a
   8: 0x7f2d3bed430b - tokio::runtime::scheduler::multi_thread::worker::run::h49404835eeeef5f3
   9: 0x7f2d3b8cb7ac - tokio::runtime::task::raw::poll::h0083a76dc5421f13
  10: 0x7f2d3bee3ef5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1fadac6c4946e153
  11: 0x7f2d3bee48ef - core::ops::function::FnOnce::call_once{{vtable.shim}}::h6a8293dca237876c
  12: 0x7f2d3becc4b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha99802c2c52ada61
                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861
                 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha39aea1c57e28a15
                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861
                 - std::sys::unix::thread::Thread::new::thread_start::h9f8e3d72b1f7662f
                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys/unix/thread.rs:108
  13: 0x7f2d3d3d3609 - start_thread
  14: 0x7f2d3d50d133 - clone
  15:        0x0 - <unresolved>'''

**Comment by adbenitez** [comment]
hi @raymand211092, sorry the late reply, is this problem still present for you with the latest release of the deltachat core? it seems like a bug in tokio and it was fixed IIRC
