### ISSUE TITLE
TypeError("quote_from_bytes() expected bytes")

### ISSUE THREAD

**Issue by genya1** [simplebot-org/simplebot#71]
OS: Linux
Python version: 3.9

After running `simplebot init "addr" "pass"`, I am receiving the below error when running `simplebot info` or `simplebot db`:
```
Traceback (most recent call last):
  File "deltachat-core-rust/python/venv/bin/simplebot", line 8, in <module>
    sys.exit(main())
  File "deltachat-core-rust/python/venv/lib/python3.9/site-packages/simplebot/main.py", line 18, in main
    parser = get_base_parser(plugin_manager=pm, argv=argv)
  File "deltachat-core-rust/python/venv/lib/python3.9/site-packages/simplebot/parser.py", line 151, in get_base_parser
    args.basedir = addr and get_account_path(addr)
  File "deltachat-core-rust/python/venv/lib/python3.9/site-packages/simplebot/utils.py", line 50, in get_account_path
    return os.path.join(get_config_folder(), "accounts", quote(address))
  File "/usr/lib/python3.9/urllib/parse.py", line 862, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.9/urllib/parse.py", line 887, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

I took a look at utils.py line 50 and debugged that the address variable is a tuple and the address is in the first index, so I tried doing `quote(address[0])` but then started recieving other intialization errors. Could you please help understand the issue ?

Side note: I was able to successfully setup the simplebot on another one of my machines running Linux and Python 3.7, I am recieving this error after trying to put it on my machine that has Python 3.9 and pulling in all the new changes from gtithub.

**Comment by adbenitez** [comment]
@genya1  will check it, thanks for the report, also notice that officially Python 3.9 is not supported

**Comment by adbenitez** [comment]
@genya1 could you say what is the content of that address list you tried to do `address[0]`, add a `print("ADDRESS:", address)` instead, and what is the content of `~/.config/simplebot/global.cfg` ???

if the content is private addresses you can use `["addr1@example.org", "addr2@example.org"]` etc. when sharing here

**Comment by adbenitez** [comment]
I found the bug, will fix it, thanks for the report!

**Comment by genya1** [comment]
Thank you!
