### ISSUE TITLE
Service installation

### ISSUE THREAD

**Issue by EchedeyLR** [simplebot-org/simplebot#80]
I was thinking in a generator for SysVInit, systemd or OpenRC like https://github.com/cloudflare/cloudflared/blob/master/cmd/cloudflared/linux_service.go (this is only dedicated to SysVinit and systemd).

In this way, would have integration with different systems.

Providing only a SysVInit file is also a solution for nearly all environments (systemd has compatibility over it and the same happens with OpenRC).

**Comment by adbenitez** [comment]
this is the script I use to create a service for my simplebot instances: https://github.com/simplebot-org/simplebot/blob/master/scripts/create_service.py

**Comment by EchedeyLR** [comment]
That is only compatible with SystemD, where my question was more abstract and allowing other init systems.
