### ISSUE TITLE
Create Munin plugin for monitoring

### ISSUE THREAD

**Issue by EchedeyLR** [simplebot-org/simplebot#81]
[Munin](https://munin-monitoring.org/) is a resource monitoring software tool for computers.

Sources: 
* http://guide.munin-monitoring.org/en/latest/plugin/writing.html
* http://guide.munin-monitoring.org/en/latest/develop/plugins/howto-write-plugins.html#howto-write-plugins

Given that this is very near to email servers, postfix and exim plugins could help to get an idea of what to show. Plugins available at https://gallery.munin-monitoring.org/.

**Comment by adbenitez** [comment]
this would be nice but probably better for a 3rd party project, I don't I would have time for this and I don't have much use for it myself, and currently I am the main client of simplebot :D
